# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat',
            new_name='user',
        ),
    ]
