# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbox', '0003_auto_20170505_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(max_length=20)),
                ('chat', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
